### ISSUE TITLE
Any update in this year?

### ISSUE THREAD

**Issue by Twilightssuperb** [yulon/emoji-box#6]
Your extension was removed from Chrome Web Store. From GitHub repo I've noticed you closed some commits in February, but I can download newer version of CRX only from nowhere.

**Comment by yulon** [comment]
Due to the new policy of the Chrome Web Store, I was not told what violated, but could not submit this extension. I may stop updating.

**Comment by Twilightssuperb** [comment]
Just thanks for newer version publishing here.

Well, maybe, you could upload Emoji box again at CWS or it's so cumbersome, your CWS account had been restricted by Google?
